services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8080:8080

  jaeger:
    image: jaegertracing/all-in-one:1.55
    ports:
      - 16686:16686
      - 14268:14268
      - 9411:9411
      - 4317:4317
      - 4318:4318
